### ISSUE TITLE
help error Block unlocker died, spawning replacement...

### ISSUE THREAD

**Issue by sanich-rd** [alloy-project/alloy#30]
TypeError: Object true has no method 'map'
    at async.waterfall.orphanCommands (/home/san/pool/lib/blockUnlocker.js:82:40)
    at nextTask (/home/san/pool/node_modules/async/dist/async.js:5310:14)
    at next (/home/san/pool/node_modules/async/dist/async.js:5317:9)
    at /home/san/pool/node_modules/async/dist/async.js:958:16
    at /home/san/pool/lib/blockUnlocker.js:75:17
    at /home/san/pool/node_modules/async/dist/async.js:3358:25
    at /home/san/pool/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/san/pool/node_modules/async/dist/async.js:1048:13)
    at /home/san/pool/node_modules/async/dist/async.js:958:16
    at /home/san/pool/node_modules/async/dist/async.js:3355:13

--------------------
setting
----------------------
package.json

{
    "name": "cryptonote-universal-pool",
    "version": "0.0.1",
    "license": "GPL-2.0",
    "author": "Matthew Little",
    "repository": {
        "type": "git",
        "url": "https://github.com/fancoder/cryptonote-universal-pool.git"
    },
    "dependencies": {
        "bignum": "*",
        "async": "*",
        "redis": "*",
        "cli-color": "*",
        "dateformat": "*",
        "base58-native": "*",
        "multi-hashing": "git://github.com/fancoder/node-multi-hashing.git",
        "cryptonote-util": "git://github.com/forknote/node-cryptonote-util.git"
    },
    "engines": {
        "node": ">=0.10"
    }
}

--------------------------------
config.json

{
    "coin": "Alloy",
    "symbol": "XAO",
    "coinUnits": 1000000000000,
    "coinDifficultyTarget": 180,

    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },
        "console": {
            "level": "info",
            "colors": true
        }
    },

    "poolServer": {
        "enabled": true,
        "clusterForks": "auto",
        "poolAddress": "xxxxxxxxxx",
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,
        "ports": [
            {
                "port": 4444,
                "difficulty": 100,
                "desc": "CPU Rigs"
            },
            {
                "port": 5555,
                "difficulty": 10000,
                "desc": "GPU Rigs"
            },
            {
                "port": 7777,
                "difficulty": 500000,
                "desc": "Multiple GPU Rigs over 50KH/s+ or use Fixed Diff"
            }
        ],
        "varDiff": {
            "minDiff": 100,
            "maxDiff": 50000,
            "targetTime": 100,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
        },
        "fixedDiff": {
            "enabled": true,
            "addressSeparator": "."
        },
        "shareTrust": {
            "enabled": true,
            "min": 10,
            "stepDown": 3,
            "threshold": 10,
            "penalty": 30
        },
        "banning": {
            "enabled": true,
            "time": 20,
            "invalidPercent": 25,
            "checkThreshold": 30
        },
"slushMining": {
"enabled": false,
"weight": 120,
"lastBlockCheckRate": 1
}
    },

    "payments": {
        "enabled": true,
        "interval": 180,
        "maxAddresses": 40,
        "mixin": 0,
        "transferFee": 10000000000,
        "minPayment": 2000000000000,
        "maxTransactionAmount": 1000000000000000,
        "denomination": 1000000000
    },

    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth": 30,
        "poolFee": 1.0,
        "devDonation": 0,
        "coreDevDonation": 0.0,
        "extraFeaturesDevDonation":0
    },

    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 10,
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "password": "xxxxxxxxxxxxx"
    },

    "daemon": {
        "host": "127.0.0.1",
        "port": 1811
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 1812
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379
    },

    "monitoring": {
        "daemon": {
            "checkInterval": 60,
            "rpcMethod": "getblockcount"
        },
        "wallet": {
            "checkInterval": 60,
            "rpcMethod": "getbalance"
        }
    },

    "charts": {
        "pool": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "workers": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "difficulty": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "price": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "profit": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            }
        },
        "user": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 180,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "payments": {
                "enabled": true
            }
        }
    }
}

--------------

**Comment by sanich-rd** [comment]
The balance of the wallet the coins are credited. The miners coins are not distributed.

**Comment by sanich-rd** [comment]
Maybe the problem is "cryptonote-util": "git://github.com/forknote/node-cryptonote-util.git"
??????

**Comment by sanich-rd** [comment]
found the cause and decided. Thank You!
